const tt = [
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Climbing Stairs",
    URL: "https://leetcode.com/problems/climbing-stairs",
    Difficulty: "Easy",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Best Time to Buy and Sell Stock",
    URL: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock",
    Difficulty: "Easy",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Min Cost Climbing Stairs",
    URL: "https://leetcode.com/problems/min-cost-climbing-stairs",
    Difficulty: "Easy",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Divisor Game",
    URL: "https://leetcode.com/problems/divisor-game",
    Difficulty: "Easy",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Best Time to Buy and Sell Stock III",
    URL: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii",
    Difficulty: "Hard",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Student Attendance Record II",
    URL: "https://leetcode.com/problems/student-attendance-record-ii",
    Difficulty: "Hard",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Decode Ways II",
    URL: "https://leetcode.com/problems/decode-ways-ii",
    Difficulty: "Hard",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Triples with Bitwise AND Equal To Zero",
    URL: "https://leetcode.com/problems/triples-with-bitwise-and-equal-to-zero",
    Difficulty: "Hard",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Maximum Profit in Job Scheduling",
    URL: "https://leetcode.com/problems/maximum-profit-in-job-scheduling",
    Difficulty: "Hard",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Minimum Number of Taps to Open to Water a Garden",
    URL: "https://leetcode.com/problems/minimum-number-of-taps-to-open-to-water-a-garden",
    Difficulty: "Hard",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Count All Valid Pickup and Delivery Options",
    URL: "https://leetcode.com/problems/count-all-valid-pickup-and-delivery-options",
    Difficulty: "Hard",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Stone Game III",
    URL: "https://leetcode.com/problems/stone-game-iii",
    Difficulty: "Hard",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Restore The Array",
    URL: "https://leetcode.com/problems/restore-the-array",
    Difficulty: "Hard",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Form Largest Integer With Digits That Add up to Target",
    URL: "https://leetcode.com/problems/form-largest-integer-with-digits-that-add-up-to-target",
    Difficulty: "Hard",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Stone Game IV",
    URL: "https://leetcode.com/problems/stone-game-iv",
    Difficulty: "Hard",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Decode Ways",
    URL: "https://leetcode.com/problems/decode-ways",
    Difficulty: "Medium",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Unique Binary Search Trees",
    URL: "https://leetcode.com/problems/unique-binary-search-trees",
    Difficulty: "Medium",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "House Robber",
    URL: "https://leetcode.com/problems/house-robber",
    Difficulty: "Medium",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Perfect Squares",
    URL: "https://leetcode.com/problems/perfect-squares",
    Difficulty: "Medium",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Best Time to Buy and Sell Stock with Cooldown",
    URL: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown",
    Difficulty: "Medium",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Coin Change",
    URL: "https://leetcode.com/problems/coin-change",
    Difficulty: "Medium",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Counting Bits",
    URL: "https://leetcode.com/problems/counting-bits",
    Difficulty: "Medium",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Integer Break",
    URL: "https://leetcode.com/problems/integer-break",
    Difficulty: "Medium",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Count Numbers with Unique Digits",
    URL: "https://leetcode.com/problems/count-numbers-with-unique-digits",
    Difficulty: "Medium",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Wiggle Subsequence",
    URL: "https://leetcode.com/problems/wiggle-subsequence",
    Difficulty: "Medium",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Partition Equal Subset Sum",
    URL: "https://leetcode.com/problems/partition-equal-subset-sum",
    Difficulty: "Medium",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Maximum Length of Pair Chain",
    URL: "https://leetcode.com/problems/maximum-length-of-pair-chain",
    Difficulty: "Medium",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Best Time to Buy and Sell Stock with Transaction Fee",
    URL: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee",
    Difficulty: "Medium",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Delete and Earn",
    URL: "https://leetcode.com/problems/delete-and-earn",
    Difficulty: "Medium",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Domino and Tromino Tiling",
    URL: "https://leetcode.com/problems/domino-and-tromino-tiling",
    Difficulty: "Medium",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Knight Dialer",
    URL: "https://leetcode.com/problems/knight-dialer",
    Difficulty: "Medium",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Minimum Cost For Tickets",
    URL: "https://leetcode.com/problems/minimum-cost-for-tickets",
    Difficulty: "Medium",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Partition Array for Maximum Sum",
    URL: "https://leetcode.com/problems/partition-array-for-maximum-sum",
    Difficulty: "Medium",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Filling Bookcase Shelves",
    URL: "https://leetcode.com/problems/filling-bookcase-shelves",
    Difficulty: "Medium",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Longest Arithmetic Subsequence of Given Difference",
    URL: "https://leetcode.com/problems/longest-arithmetic-subsequence-of-given-difference",
    Difficulty: "Medium",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Greatest Sum Divisible by Three",
    URL: "https://leetcode.com/problems/greatest-sum-divisible-by-three",
    Difficulty: "Medium",
    Category: "1.Linear DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Profitable Schemes",
    URL: "https://leetcode.com/problems/profitable-schemes",
    Difficulty: "Hard",
    Category: "2.Knapsack",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Tallest Billboard",
    URL: "https://leetcode.com/problems/tallest-billboard",
    Difficulty: "Hard",
    Category: "2.Knapsack",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Pizza With 3n Slices",
    URL: "https://leetcode.com/problems/pizza-with-3n-slices",
    Difficulty: "Hard",
    Category: "2.Knapsack",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Reducing Dishes",
    URL: "https://leetcode.com/problems/reducing-dishes",
    Difficulty: "Hard",
    Category: "2.Knapsack",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "House Robber II",
    URL: "https://leetcode.com/problems/house-robber-ii",
    Difficulty: "Medium",
    Category: "2.Knapsack",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Ones and Zeroes",
    URL: "https://leetcode.com/problems/ones-and-zeroes",
    Difficulty: "Medium",
    Category: "2.Knapsack",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Target Sum",
    URL: "https://leetcode.com/problems/target-sum",
    Difficulty: "Medium",
    Category: "2.Knapsack",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Shopping Offers",
    URL: "https://leetcode.com/problems/shopping-offers",
    Difficulty: "Medium",
    Category: "2.Knapsack",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "2 Keys Keyboard",
    URL: "https://leetcode.com/problems/2-keys-keyboard",
    Difficulty: "Medium",
    Category: "2.Knapsack",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Minimum Swaps To Make Sequences Increasing",
    URL: "https://leetcode.com/problems/minimum-swaps-to-make-sequences-increasing",
    Difficulty: "Medium",
    Category: "2.Knapsack",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Best Team With No Conflicts",
    URL: "https://leetcode.com/problems/best-team-with-no-conflicts",
    Difficulty: "Medium",
    Category: "2.Knapsack",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Best Time to Buy and Sell Stock IV",
    URL: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv",
    Difficulty: "Hard",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Create Maximum Number",
    URL: "https://leetcode.com/problems/create-maximum-number",
    Difficulty: "Hard",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Frog Jump",
    URL: "https://leetcode.com/problems/frog-jump",
    Difficulty: "Hard",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Split Array Largest Sum",
    URL: "https://leetcode.com/problems/split-array-largest-sum",
    Difficulty: "Hard",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Freedom Trail",
    URL: "https://leetcode.com/problems/freedom-trail",
    Difficulty: "Hard",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Minimum Number of Refueling Stops",
    URL: "https://leetcode.com/problems/minimum-number-of-refueling-stops",
    Difficulty: "Hard",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Number of Music Playlists",
    URL: "https://leetcode.com/problems/number-of-music-playlists",
    Difficulty: "Hard",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Count Vowels Permutation",
    URL: "https://leetcode.com/problems/count-vowels-permutation",
    Difficulty: "Hard",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Minimum Falling Path Sum II",
    URL: "https://leetcode.com/problems/minimum-falling-path-sum-ii",
    Difficulty: "Hard",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Minimum Distance to Type a Word Using Two Fingers",
    URL: "https://leetcode.com/problems/minimum-distance-to-type-a-word-using-two-fingers",
    Difficulty: "Hard",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Minimum Difficulty of a Job Schedule",
    URL: "https://leetcode.com/problems/minimum-difficulty-of-a-job-schedule",
    Difficulty: "Hard",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Number of Ways to Paint Nx3 Grid",
    URL: "https://leetcode.com/problems/number-of-ways-to-paint-n-3-grid",
    Difficulty: "Hard",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Build Array Where You Can Find The Maximum Exactly K Comparisons",
    URL: "https://leetcode.com/problems/build-array-where-you-can-find-the-maximum-exactly-k-comparisons",
    Difficulty: "Hard",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Number of Ways of Cutting a Pizza",
    URL: "https://leetcode.com/problems/number-of-ways-of-cutting-a-pizza",
    Difficulty: "Hard",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Paint House III",
    URL: "https://leetcode.com/problems/paint-house-iii",
    Difficulty: "Hard",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Count All Possible Routes",
    URL: "https://leetcode.com/problems/count-all-possible-routes",
    Difficulty: "Hard",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Triangle",
    URL: "https://leetcode.com/problems/triangle",
    Difficulty: "Medium",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Combination Sum IV",
    URL: "https://leetcode.com/problems/combination-sum-iv",
    Difficulty: "Medium",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Out of Boundary Paths",
    URL: "https://leetcode.com/problems/out-of-boundary-paths",
    Difficulty: "Medium",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Knight Probability in Chessboard",
    URL: "https://leetcode.com/problems/knight-probability-in-chessboard",
    Difficulty: "Medium",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Champagne Tower",
    URL: "https://leetcode.com/problems/champagne-tower",
    Difficulty: "Medium",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Largest Sum of Averages",
    URL: "https://leetcode.com/problems/largest-sum-of-averages",
    Difficulty: "Medium",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Minimum Falling Path Sum",
    URL: "https://leetcode.com/problems/minimum-falling-path-sum",
    Difficulty: "Medium",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Video Stitching",
    URL: "https://leetcode.com/problems/video-stitching",
    Difficulty: "Medium",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Longest Arithmetic Subsequence",
    URL: "https://leetcode.com/problems/longest-arithmetic-subsequence",
    Difficulty: "Medium",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Stone Game II",
    URL: "https://leetcode.com/problems/stone-game-ii",
    Difficulty: "Medium",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Number of Dice Rolls With Target Sum",
    URL: "https://leetcode.com/problems/number-of-dice-rolls-with-target-sum",
    Difficulty: "Medium",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Dice Roll Simulation",
    URL: "https://leetcode.com/problems/dice-roll-simulation",
    Difficulty: "Medium",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Number of Sets of K Non-Overlapping Line Segments",
    URL: "https://leetcode.com/problems/number-of-sets-of-k-non-overlapping-line-segments",
    Difficulty: "Medium",
    Category: "3.Multi Dimensions DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Palindrome Partitioning II",
    URL: "https://leetcode.com/problems/palindrome-partitioning-ii",
    Difficulty: "Hard",
    Category: "4.Interval DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Burst Balloons",
    URL: "https://leetcode.com/problems/burst-balloons",
    Difficulty: "Hard",
    Category: "4.Interval DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Remove Boxes",
    URL: "https://leetcode.com/problems/remove-boxes",
    Difficulty: "Hard",
    Category: "4.Interval DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Strange Printer",
    URL: "https://leetcode.com/problems/strange-printer",
    Difficulty: "Hard",
    Category: "4.Interval DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Valid Permutations for DI Sequence",
    URL: "https://leetcode.com/problems/valid-permutations-for-di-sequence",
    Difficulty: "Hard",
    Category: "4.Interval DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Minimum Cost to Merge Stones",
    URL: "https://leetcode.com/problems/minimum-cost-to-merge-stones",
    Difficulty: "Hard",
    Category: "4.Interval DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Allocate Mailboxes",
    URL: "https://leetcode.com/problems/allocate-mailboxes",
    Difficulty: "Hard",
    Category: "4.Interval DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Minimum Cost to Cut a Stick",
    URL: "https://leetcode.com/problems/minimum-cost-to-cut-a-stick",
    Difficulty: "Hard",
    Category: "4.Interval DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Stone Game V",
    URL: "https://leetcode.com/problems/stone-game-v",
    Difficulty: "Hard",
    Category: "4.Interval DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Guess Number Higher or Lower II",
    URL: "https://leetcode.com/problems/guess-number-higher-or-lower-ii",
    Difficulty: "Medium",
    Category: "4.Interval DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Arithmetic Slices",
    URL: "https://leetcode.com/problems/arithmetic-slices",
    Difficulty: "Medium",
    Category: "4.Interval DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Predict the Winner",
    URL: "https://leetcode.com/problems/predict-the-winner",
    Difficulty: "Medium",
    Category: "4.Interval DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Palindromic Substrings",
    URL: "https://leetcode.com/problems/palindromic-substrings",
    Difficulty: "Medium",
    Category: "4.Interval DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Stone Game",
    URL: "https://leetcode.com/problems/stone-game",
    Difficulty: "Medium",
    Category: "4.Interval DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Minimum Score Triangulation of Polygon",
    URL: "https://leetcode.com/problems/minimum-score-triangulation-of-polygon",
    Difficulty: "Medium",
    Category: "4.Interval DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Last Stone Weight II",
    URL: "https://leetcode.com/problems/last-stone-weight-ii",
    Difficulty: "Medium",
    Category: "4.Interval DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Minimum Cost Tree From Leaf Values",
    URL: "https://leetcode.com/problems/minimum-cost-tree-from-leaf-values",
    Difficulty: "Medium",
    Category: "4.Interval DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Stone Game VII",
    URL: "https://leetcode.com/problems/stone-game-vii",
    Difficulty: "Medium",
    Category: "4.Interval DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Stickers to Spell Word",
    URL: "https://leetcode.com/problems/stickers-to-spell-word",
    Difficulty: "Hard",
    Category: "5.bit DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Shortest Path Visiting All Nodes",
    URL: "https://leetcode.com/problems/shortest-path-visiting-all-nodes",
    Difficulty: "Hard",
    Category: "5.bit DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Smallest Sufficient Team",
    URL: "https://leetcode.com/problems/smallest-sufficient-team",
    Difficulty: "Hard",
    Category: "5.bit DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Maximum Students Taking Exam",
    URL: "https://leetcode.com/problems/maximum-students-taking-exam",
    Difficulty: "Hard",
    Category: "5.bit DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Number of Ways to Wear Different Hats to Each Other",
    URL: "https://leetcode.com/problems/number-of-ways-to-wear-different-hats-to-each-other",
    Difficulty: "Hard",
    Category: "5.bit DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Minimum Cost to Connect Two Groups of Points",
    URL: "https://leetcode.com/problems/minimum-cost-to-connect-two-groups-of-points",
    Difficulty: "Hard",
    Category: "5.bit DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Maximum Number of Achievable Transfer Requests",
    URL: "https://leetcode.com/problems/maximum-number-of-achievable-transfer-requests",
    Difficulty: "Hard",
    Category: "5.bit DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Distribute Repeating Integers",
    URL: "https://leetcode.com/problems/distribute-repeating-integers",
    Difficulty: "Hard",
    Category: "5.bit DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Maximize Grid Happiness",
    URL: "https://leetcode.com/problems/maximize-grid-happiness",
    Difficulty: "Hard",
    Category: "5.bit DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Can I Win",
    URL: "https://leetcode.com/problems/can-i-win",
    Difficulty: "Medium",
    Category: "5.bit DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Partition to K Equal Sum Subsets",
    URL: "https://leetcode.com/problems/partition-to-k-equal-sum-subsets",
    Difficulty: "Medium",
    Category: "5.bit DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Non-negative Integers without Consecutive Ones",
    URL: "https://leetcode.com/problems/non-negative-integers-without-consecutive-ones",
    Difficulty: "Hard",
    Category: "6.Digit DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Numbers At Most N Given Digit Set",
    URL: "https://leetcode.com/problems/numbers-at-most-n-given-digit-set",
    Difficulty: "Hard",
    Category: "6.Digit DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Numbers With Repeated Digits",
    URL: "https://leetcode.com/problems/numbers-with-repeated-digits",
    Difficulty: "Hard",
    Category: "6.Digit DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Binary Tree Cameras",
    URL: "https://leetcode.com/problems/binary-tree-cameras",
    Difficulty: "Hard",
    Category: "7.DP on Trees",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Maximum Sum BST in Binary Tree",
    URL: "https://leetcode.com/problems/maximum-sum-bst-in-binary-tree",
    Difficulty: "Hard",
    Category: "7.DP on Trees",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Number of Ways to Reorder Array to Get Same BST",
    URL: "https://leetcode.com/problems/number-of-ways-to-reorder-array-to-get-same-bst",
    Difficulty: "Hard",
    Category: "7.DP on Trees",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Unique Binary Search Trees II",
    URL: "https://leetcode.com/problems/unique-binary-search-trees-ii",
    Difficulty: "Medium",
    Category: "7.DP on Trees",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "House Robber III",
    URL: "https://leetcode.com/problems/house-robber-iii",
    Difficulty: "Medium",
    Category: "7.DP on Trees",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Maximum Product of Splitted Binary Tree",
    URL: "https://leetcode.com/problems/maximum-product-of-splitted-binary-tree",
    Difficulty: "Medium",
    Category: "7.DP on Trees",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Linked List in Binary Tree",
    URL: "https://leetcode.com/problems/linked-list-in-binary-tree",
    Difficulty: "Medium",
    Category: "7.DP on Trees",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Longest ZigZag Path in a Binary Tree",
    URL: "https://leetcode.com/problems/longest-zigzag-path-in-a-binary-tree",
    Difficulty: "Medium",
    Category: "7.DP on Trees",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Is Subsequence",
    URL: "https://leetcode.com/problems/is-subsequence",
    Difficulty: "Easy",
    Category: "8.String DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Longest Valid Parentheses",
    URL: "https://leetcode.com/problems/longest-valid-parentheses",
    Difficulty: "Hard",
    Category: "8.String DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Distinct Subsequences",
    URL: "https://leetcode.com/problems/distinct-subsequences",
    Difficulty: "Hard",
    Category: "8.String DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Word Break II",
    URL: "https://leetcode.com/problems/word-break-ii",
    Difficulty: "Hard",
    Category: "8.String DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Count The Repetitions",
    URL: "https://leetcode.com/problems/count-the-repetitions",
    Difficulty: "Hard",
    Category: "8.String DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Concatenated Words",
    URL: "https://leetcode.com/problems/concatenated-words",
    Difficulty: "Hard",
    Category: "8.String DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Count Different Palindromic Subsequences",
    URL: "https://leetcode.com/problems/count-different-palindromic-subsequences",
    Difficulty: "Hard",
    Category: "8.String DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Distinct Subsequences II",
    URL: "https://leetcode.com/problems/distinct-subsequences-ii",
    Difficulty: "Hard",
    Category: "8.String DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Longest Chunked Palindrome Decomposition",
    URL: "https://leetcode.com/problems/longest-chunked-palindrome-decomposition",
    Difficulty: "Hard",
    Category: "8.String DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Palindrome Partitioning III",
    URL: "https://leetcode.com/problems/palindrome-partitioning-iii",
    Difficulty: "Hard",
    Category: "8.String DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Find All Good Strings",
    URL: "https://leetcode.com/problems/find-all-good-strings",
    Difficulty: "Hard",
    Category: "8.String DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "String Compression II",
    URL: "https://leetcode.com/problems/string-compression-ii",
    Difficulty: "Hard",
    Category: "8.String DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Number of Ways to Form a Target String Given a Dictionary",
    URL: "https://leetcode.com/problems/number-of-ways-to-form-a-target-string-given-a-dictionary",
    Difficulty: "Hard",
    Category: "8.String DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Palindrome Partitioning",
    URL: "https://leetcode.com/problems/palindrome-partitioning",
    Difficulty: "Medium",
    Category: "8.String DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Word Break",
    URL: "https://leetcode.com/problems/word-break",
    Difficulty: "Medium",
    Category: "8.String DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Unique Substrings in Wraparound String",
    URL: "https://leetcode.com/problems/unique-substrings-in-wraparound-string",
    Difficulty: "Medium",
    Category: "8.String DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Minimum ASCII Delete Sum for Two Strings",
    URL: "https://leetcode.com/problems/minimum-ascii-delete-sum-for-two-strings",
    Difficulty: "Medium",
    Category: "8.String DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Longest String Chain",
    URL: "https://leetcode.com/problems/longest-string-chain",
    Difficulty: "Medium",
    Category: "8.String DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Longest Happy String",
    URL: "https://leetcode.com/problems/longest-happy-string",
    Difficulty: "Medium",
    Category: "8.String DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Soup Servings",
    URL: "https://leetcode.com/problems/soup-servings",
    Difficulty: "Medium",
    Category: "9.Probability DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "New 21 Game",
    URL: "https://leetcode.com/problems/new-21-game",
    Difficulty: "Medium",
    Category: "9.Probability DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Airplane Seat Assignment Probability",
    URL: "https://leetcode.com/problems/airplane-seat-assignment-probability",
    Difficulty: "Medium",
    Category: "9.Probability DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Maximum Subarray",
    URL: "https://leetcode.com/problems/maximum-subarray",
    Difficulty: "Easy",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Maximum Product Subarray",
    URL: "https://leetcode.com/problems/maximum-product-subarray",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Bitwise ORs of Subarrays",
    URL: "https://leetcode.com/problems/bitwise-ors-of-subarrays",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Longest Turbulent Subarray",
    URL: "https://leetcode.com/problems/longest-turbulent-subarray",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Maximum Subarray Sum with One Deletion",
    URL: "https://leetcode.com/problems/maximum-subarray-sum-with-one-deletion",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "K-Concatenation Maximum Sum",
    URL: "https://leetcode.com/problems/k-concatenation-maximum-sum",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Largest Divisible Subset",
    URL: "https://leetcode.com/problems/largest-divisible-subset",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Length of Longest Fibonacci Subsequence",
    URL: "https://leetcode.com/problems/length-of-longest-fibonacci-subsequence",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Regular Expression Matching",
    URL: "https://leetcode.com/problems/regular-expression-matching",
    Difficulty: "Hard",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Wildcard Matching",
    URL: "https://leetcode.com/problems/wildcard-matching",
    Difficulty: "Hard",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Edit Distance",
    URL: "https://leetcode.com/problems/edit-distance",
    Difficulty: "Hard",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Interleaving String",
    URL: "https://leetcode.com/problems/interleaving-string",
    Difficulty: "Hard",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Shortest Common Supersequence",
    URL: "https://leetcode.com/problems/shortest-common-supersequence",
    Difficulty: "Hard",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Minimum Insertion Steps to Make a String Palindrome",
    URL: "https://leetcode.com/problems/minimum-insertion-steps-to-make-a-string-palindrome",
    Difficulty: "Hard",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Max Dot Product of Two Subsequences",
    URL: "https://leetcode.com/problems/max-dot-product-of-two-subsequences",
    Difficulty: "Hard",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Longest Palindromic Substring",
    URL: "https://leetcode.com/problems/longest-palindromic-substring",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Longest Palindromic Subsequence",
    URL: "https://leetcode.com/problems/longest-palindromic-subsequence",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Maximum Length of Repeated Subarray",
    URL: "https://leetcode.com/problems/maximum-length-of-repeated-subarray",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Longest Common Subsequence",
    URL: "https://leetcode.com/problems/longest-common-subsequence",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Russian Doll Envelopes",
    URL: "https://leetcode.com/problems/russian-doll-envelopes",
    Difficulty: "Hard",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Delete Columns to Make Sorted III",
    URL: "https://leetcode.com/problems/delete-columns-to-make-sorted-iii",
    Difficulty: "Hard",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Make Array Strictly Increasing",
    URL: "https://leetcode.com/problems/make-array-strictly-increasing",
    Difficulty: "Hard",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Minimum Number of Removals to Make Mountain Array",
    URL: "https://leetcode.com/problems/minimum-number-of-removals-to-make-mountain-array",
    Difficulty: "Hard",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Maximum Height by Stacking Cuboids",
    URL: "https://leetcode.com/problems/maximum-height-by-stacking-cuboids",
    Difficulty: "Hard",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Longest Increasing Subsequence",
    URL: "https://leetcode.com/problems/longest-increasing-subsequence",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Number of Longest Increasing Subsequence",
    URL: "https://leetcode.com/problems/number-of-longest-increasing-subsequence",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Dungeon Game",
    URL: "https://leetcode.com/problems/dungeon-game",
    Difficulty: "Hard",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Cherry Pickup",
    URL: "https://leetcode.com/problems/cherry-pickup",
    Difficulty: "Hard",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Number of Paths with Max Score",
    URL: "https://leetcode.com/problems/number-of-paths-with-max-score",
    Difficulty: "Hard",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Cherry Pickup II",
    URL: "https://leetcode.com/problems/cherry-pickup-ii",
    Difficulty: "Hard",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Kth Smallest Instructions",
    URL: "https://leetcode.com/problems/kth-smallest-instructions",
    Difficulty: "Hard",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Unique Paths",
    URL: "https://leetcode.com/problems/unique-paths",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Unique Paths II",
    URL: "https://leetcode.com/problems/unique-paths-ii",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Minimum Path Sum",
    URL: "https://leetcode.com/problems/minimum-path-sum",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Maximum Non Negative Product in a Matrix",
    URL: "https://leetcode.com/problems/maximum-non-negative-product-in-a-matrix",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Where Will the Ball Fall",
    URL: "https://leetcode.com/problems/where-will-the-ball-fall",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Range Sum Query - Immutable",
    URL: "https://leetcode.com/problems/range-sum-query-immutable",
    Difficulty: "Easy",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Maximal Rectangle",
    URL: "https://leetcode.com/problems/maximal-rectangle",
    Difficulty: "Hard",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Max Sum of Rectangle No Larger Than K",
    URL: "https://leetcode.com/problems/max-sum-of-rectangle-no-larger-than-k",
    Difficulty: "Hard",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Super Washing Machines",
    URL: "https://leetcode.com/problems/super-washing-machines",
    Difficulty: "Hard",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Maximum Sum of 3 Non-Overlapping Subarrays",
    URL: "https://leetcode.com/problems/maximum-sum-of-3-non-overlapping-subarrays",
    Difficulty: "Hard",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Number of Submatrices That Sum to Target",
    URL: "https://leetcode.com/problems/number-of-submatrices-that-sum-to-target",
    Difficulty: "Hard",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Get the Maximum Score",
    URL: "https://leetcode.com/problems/get-the-maximum-score",
    Difficulty: "Hard",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Maximal Square",
    URL: "https://leetcode.com/problems/maximal-square",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Range Sum Query 2D - Immutable",
    URL: "https://leetcode.com/problems/range-sum-query-2d-immutable",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Largest Plus Sign",
    URL: "https://leetcode.com/problems/largest-plus-sign",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Push Dominoes",
    URL: "https://leetcode.com/problems/push-dominoes",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Largest 1-Bordered Square",
    URL: "https://leetcode.com/problems/largest-1-bordered-square",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Count Square Submatrices with All Ones",
    URL: "https://leetcode.com/problems/count-square-submatrices-with-all-ones",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Matrix Block Sum",
    URL: "https://leetcode.com/problems/matrix-block-sum",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Maximum Points You Can Obtain from Cards",
    URL: "https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Count Submatrices With All Ones",
    URL: "https://leetcode.com/problems/count-submatrices-with-all-ones",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Ways to Make a Fair Array",
    URL: "https://leetcode.com/problems/ways-to-make-a-fair-array",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Continuous Subarray Sum",
    URL: "https://leetcode.com/problems/continuous-subarray-sum",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Find Two Non-overlapping Sub-arrays Each With Target Sum",
    URL: "https://leetcode.com/problems/find-two-non-overlapping-sub-arrays-each-with-target-sum",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Maximum Number of Non-Overlapping Subarrays With Sum Equals Target",
    URL: "https://leetcode.com/problems/maximum-number-of-non-overlapping-subarrays-with-sum-equals-target",
    Difficulty: "Medium",
    Category: "10.Classic DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Arithmetic Slices II - Subsequence",
    URL: "https://leetcode.com/problems/arithmetic-slices-ii-subsequence",
    Difficulty: "Hard",
    Category: "11. DP + Alpha (Tricks/DS)",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Odd Even Jump",
    URL: "https://leetcode.com/problems/odd-even-jump",
    Difficulty: "Hard",
    Category: "11. DP + Alpha (Tricks/DS)",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Constrained Subsequence Sum",
    URL: "https://leetcode.com/problems/constrained-subsequence-sum",
    Difficulty: "Hard",
    Category: "11. DP + Alpha (Tricks/DS)",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Delivering Boxes from Storage to Ports",
    URL: "https://leetcode.com/problems/delivering-boxes-from-storage-to-ports",
    Difficulty: "Hard",
    Category: "11. DP + Alpha (Tricks/DS)",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "K Inverse Pairs Array",
    URL: "https://leetcode.com/problems/k-inverse-pairs-array",
    Difficulty: "Hard",
    Category: "12.Insertion DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Find the Shortest Superstring",
    URL: "https://leetcode.com/problems/find-the-shortest-superstring",
    Difficulty: "Hard",
    Category: "13.Graph DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Cheapest Flights Within K Stops",
    URL: "https://leetcode.com/problems/cheapest-flights-within-k-stops",
    Difficulty: "Medium",
    Category: "13.Graph DP",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Scramble String",
    URL: "https://leetcode.com/problems/scramble-string",
    Difficulty: "Hard",
    Category: "14.Memoization",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Tiling a Rectangle with the Fewest Squares",
    URL: "https://leetcode.com/problems/tiling-a-rectangle-with-the-fewest-squares",
    Difficulty: "Hard",
    Category: "14.Memoization",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Number of Ways to Stay in the Same Place After Some Steps",
    URL: "https://leetcode.com/problems/number-of-ways-to-stay-in-the-same-place-after-some-steps",
    Difficulty: "Hard",
    Category: "14.Memoization",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Jump Game V",
    URL: "https://leetcode.com/problems/jump-game-v",
    Difficulty: "Hard",
    Category: "14.Memoization",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Minimum Number of Days to Eat N Oranges",
    URL: "https://leetcode.com/problems/minimum-number-of-days-to-eat-n-oranges",
    Difficulty: "Hard",
    Category: "14.Memoization",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Minimum Jumps to Reach Home",
    URL: "https://leetcode.com/problems/minimum-jumps-to-reach-home",
    Difficulty: "Medium",
    Category: "14.Memoization",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Kth Ancestor of a Tree Node",
    URL: "https://leetcode.com/problems/kth-ancestor-of-a-tree-node",
    Difficulty: "Hard",
    Category: "15. Binary Lifting",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Race Car",
    URL: "https://leetcode.com/problems/race-car",
    Difficulty: "Hard",
    Category: "16. Math",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Super Egg Drop",
    URL: "https://leetcode.com/problems/super-egg-drop",
    Difficulty: "Hard",
    Category: "16. Math",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Least Operators to Express Number",
    URL: "https://leetcode.com/problems/least-operators-to-express-number",
    Difficulty: "Hard",
    Category: "16. Math",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Largest Multiple of Three",
    URL: "https://leetcode.com/problems/largest-multiple-of-three",
    Difficulty: "Hard",
    Category: "16. Math",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Minimum One Bit Operations to Make Integers Zero",
    URL: "https://leetcode.com/problems/minimum-one-bit-operations-to-make-integers-zero",
    Difficulty: "Hard",
    Category: "16. Math",
  },
  {
    Title: "",
    URL: "",
    Difficulty: "",
    Category: "",
  },
  {
    Title: "Ugly Number II",
    URL: "https://leetcode.com/problems/ugly-number-ii",
    Difficulty: "Medium",
    Category: "16. Math",
  },
  {
    Title: "",
  },
];

export default tt;
